server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///hm49?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    host: 192.168.152.130
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #过时时间
    lease-expiration-duration-in-seconds: 15  #心跳时间
mybatis:
  type-aliases-package: com.leyou.item.pojo

